### ISSUE TITLE
Open Spotify window from TrayPlay

### ISSUE THREAD

**Issue by nikoskip** [mborgerson/TrayPlay#5]
Hi!

I was bothered about the Spotify icon in my Dock (I already have to many), so I hid it using this command:

`defaults write /Applications/Spotify.app/Contents/Info.plist LSUIElement true`

But, the only problem is if I want to bring Spotify to front, I have to search the App and opon it again. It would be great if in *TrayPlay* I can open Spotify from a little icon:

![image](https://cloud.githubusercontent.com/assets/1230033/23310511/cd858ad2-fa80-11e6-803c-aae46341a30d.png)

**Comment by mborgerson** [comment]
Thanks for the feedback. Try clicking on the album artwork, that should open up the player.

**Comment by nikoskip** [comment]
I love you!

**Comment by nikoskip** [comment]
BTW, it's normal that I have to do 3 or more clicks to get a response from your app?

Check this example:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1230033/23311164/12006b9e-fa83-11e6-8959-e9a42a461a97.gif)

1st click: no response
2nd click: the app shows up
3rd click: I click on cover, nothing happens, but it seems Chrome loses focus (look how the Chrome window change its color)
4th click: Spotify opens ;)

Thanks!
